ktor:
  deployment:
    port: 8080
    host: 127.0.0.1
    sslPort: 8443
  application:
    modules:
      - ru.test.storeapp.ApplicationKt.module
  security:
    ssl:
      keyStore: keystore.jks
      keyAlias: sampleAlias
      keyStorePassword: foobar
      privateKeyPassword: foobar