ktor:
  deployment:
    port: ${?APP_PORT}
    host: ${?APP_HOST}

  application:
    modules:
      - ru.test.storeapp.ApplicationKt.module

  mongo:
    uri: ${?MONGO_URI}
    database: ${?MONGO_DB}