ktor:
  deployment:
    port: ${?APP_PORT}
    host: ${?APP_HOST}
    sslPort: ${?APP_SSL_PORT}

  application:
    modules:
      - ru.test.storeapp.ApplicationKt.module

  mongo:
    uri: ${?MONGO_URI}
    database: ${?MONGO_DB}

  security:
    ssl:
      keyStore: ${?SSL_KEYSTORE}
      keyAlias: ${?SSL_KEY_ALIAS}
      keyStorePassword: ${?SSL_KEYSTORE_PASS}
      privateKeyPassword: ${?SSL_PRIVATE_KEY_PASS}